// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package screamer

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockConsumerWithAck creates a new instance of MockConsumerWithAck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumerWithAck(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumerWithAck {
	mock := &MockConsumerWithAck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConsumerWithAck is an autogenerated mock type for the ConsumerWithAck type
type MockConsumerWithAck struct {
	mock.Mock
}

type MockConsumerWithAck_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumerWithAck) EXPECT() *MockConsumerWithAck_Expecter {
	return &MockConsumerWithAck_Expecter{mock: &_m.Mock}
}

// Consume provides a mock function for the type MockConsumerWithAck
func (_mock *MockConsumerWithAck) Consume(change []byte, ack AckFunc) error {
	ret := _mock.Called(change, ack)

	if len(ret) == 0 {
		panic("no return value specified for Consume")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte, AckFunc) error); ok {
		r0 = returnFunc(change, ack)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConsumerWithAck_Consume_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Consume'
type MockConsumerWithAck_Consume_Call struct {
	*mock.Call
}

// Consume is a helper method to define mock.On call
//   - change []byte
//   - ack AckFunc
func (_e *MockConsumerWithAck_Expecter) Consume(change interface{}, ack interface{}) *MockConsumerWithAck_Consume_Call {
	return &MockConsumerWithAck_Consume_Call{Call: _e.mock.On("Consume", change, ack)}
}

func (_c *MockConsumerWithAck_Consume_Call) Run(run func(change []byte, ack AckFunc)) *MockConsumerWithAck_Consume_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		var arg1 AckFunc
		if args[1] != nil {
			arg1 = args[1].(AckFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConsumerWithAck_Consume_Call) Return(err error) *MockConsumerWithAck_Consume_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConsumerWithAck_Consume_Call) RunAndReturn(run func(change []byte, ack AckFunc) error) *MockConsumerWithAck_Consume_Call {
	_c.Call.Return(run)
	return _c
}
